<?php

/*
 * Branding configs for your application
 */
return [
    'login' => [
        'page_title' => 'Sign in',
        'headline' => 'Sign in',
        'subheadline' => 'Login to your account below',
        'show_subheadline' => false,
        'email_address' => 'Email Address',
        'password' => 'Password',
        'remember_me' => 'Remember me',
        'edit' => 'Edit',
        'button' => 'Continue',
        'forget_password' => 'Forget your password?',
        'dont_have_an_account' => "Don't have an account?",
        'sign_up' => 'Sign up',
        'social_auth_authenticated_message' => 'You have been authenticated via __social_providers_list__. Please login to that network below.',
        'change_email' => 'Change Email',
        'couldnt_find_your_account' => 'Couldn’t find your account',
    ],
    'register' => [
        'page_title' => 'Înregistrare',
        'headline' => 'Înregistrare',
        'subheadline' => 'Înregistrați-vă pentru contul dumneavoastră gratuit.',
        'show_subheadline' => false,
        'name' => 'Nume',
        'email_address' => 'Adresa de Email',
        'password' => 'Parola',
        'password_confirmation' => 'Confirmați Parola',
        'already_have_an_account' => 'Aveți deja un cont?',
        'sign_in' => 'Conectați-vă',
        'button' => 'Continuă',
        'email_registration_disabled' => 'Înregistrarea prin email este dezactivată momentan. Vă rugăm să folosiți conectarea socială.',
    ],
    'verify' => [
        'page_title' => 'Verificați Contul',
        'headline' => 'Verificați adresa de email',
        'subheadline' => 'Înainte să puteți continua, trebuie să vă verificați email-ul.',
        'show_subheadline' => false,
        'description' => 'Înainte de a continua, vă rugăm să verificați email-ul pentru linkul de verificare. Dacă nu ați primit email-ul,',
        'new_request_link' => 'faceți clic aici pentru a solicita altul',
        'new_link_sent' => 'Un nou link a fost trimis la adresa dumneavoastră de email.',
        'or' => 'Sau',
        'logout' => 'faceți clic aici pentru a vă deconecta',
    ],
    'passwordConfirm' => [
        'page_title' => 'Confirmați Parola',
        'headline' => 'Confirmați Parola',
        'subheadline' => 'Asigurați-vă că confirmați parola mai jos',
        'show_subheadline' => false,
        'password' => 'Parola',
        'button' => 'Confirmați parola',
    ],
    'passwordResetRequest' => [
        'page_title' => 'Solicitați Resetarea Parolei',
        'headline' => 'Resetați parola',
        'subheadline' => 'Introduceți email-ul pentru a reseta parola',
        'show_subheadline' => false,
        'email' => 'Adresa de Email',
        'button' => 'Trimiteți linkul de resetare',
        'or' => 'sau',
        'return_to_login' => 'întoarceți-vă la conectare',
    ],
    'passwordReset' => [
        'page_title' => 'Resetați Parola',
        'headline' => 'Resetați Parola',
        'subheadline' => 'Resetați parola mai jos',
        'show_subheadline' => false,
        'email' => 'Adresa de Email',
        'password' => 'Parola',
        'password_confirm' => 'Confirmați Parola',
        'button' => 'Resetați Parola',
    ],
    'twoFactorChallenge' => [
        'page_title' => 'Provocare cu Doi Factori',
        'headline_auth' => 'Cod de Autentificare',
        'subheadline_auth' => 'Introduceți codul de autentificare furnizat de aplicația dumneavoastră de autentificare.',
        'show_subheadline_auth' => false,
        'headline_recovery' => 'Cod de Recuperare',
        'subheadline_recovery' => 'Vă rugăm să confirmați accesul la contul dumneavoastră introducând unul dintre codurile de recuperare de urgență.',
        'show_subheadline_recovery' => false,
    ],

];
